[workspace]
resolver = "2"
package.edition = "2021"
package.rust-version = "1.76.0"
members = [
    "crates/cubedaw",
    "crates/cubedaw-lib",
    "crates/cubedaw-worker",
    "crates/cubedaw-command",
]
