[package]
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
name = "cubedaw-plugin"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
ahash = { workspace = true }
smallvec = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
wasmparser = "0.215.0"
wasm-encoder = { version = "0.215.0", features = ["wasmparser"] }

[features]

[lints]
workspace = true
