[package]
name = "xtask"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
toml = "0.8.19"
xshell = "0.2.6"

[lints]
workspace = true
