[package]
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
name = "cubedaw"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
eframe = "0.26.2"
egui = "0.26.2"
egui_dock = "0.11.4"
env_logger = "0.11.3"
cubedaw-lib = { path = "../cubedaw-lib", features = ["egui"]}
ahash = "0.8.11"
smallvec = "1.13.2"
