[package]
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
name = "cubedaw"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
cubedaw-command = { path = "../cubedaw-command" }
egui = { workspace = true }
eframe = "0.27.2"
egui_dock = "0.12.0"
env_logger = "0.11.3"
cubedaw-lib = { path = "../cubedaw-lib", features = ["egui"] }
cubedaw-workerlib = { path = "../cubedaw-workerlib", features = ["egui"] }
cubedaw-node = { path = "../cubedaw-node", features = ["egui"] }
cubedaw-worker = { path = "../cubedaw-worker", features = ["egui"] }
ahash = { workspace = true }
smallvec = { workspace = true }
bytemuck = { workspace = true }

[lints]
workspace = true
