[package]
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
name = "cubedaw"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
bytemuck = {version = "1.14.0", features = ["must_cast"]}
ciborium = "0.2.1"
cubedaw_lib = {path = "../cubedaw_lib"}
eframe = "0.23.0"
egui = {version = "0.23.0", features = ["bytemuck"]}
egui_dock = "0.8.2"
log = "0.4"
serde = {version = "1.0.190", features = ["derive"]}

[[bin]]
name = "app"
path = "src/main.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.88"
wasm-bindgen-futures = "0.4"
