[package]
authors = ["Colin Cai <therealcreative0708@gmail.com>"]
edition.workspace = true
name = "cubedaw-lib"
rust-version.workspace = true
version = "0.1.0"

[dependencies]
ahash = "0.8.11"
smallvec = "1.13.2"
egui = { version = "0.26.2", optional = true }

[features]
egui = ["dep:egui"]
