[unstable]
codegen-backend = true

[profile.dev]
# can't use cranelift here bcuz wasmtime no likey :(
# https://github.com/rust-lang/rustc_codegen_cranelift/issues/1204
# codegen-backend = "cranelift"

[alias]
xtask = "run --package xtask --"
