[unstable]
codegen-backend = true

[profile.dev]
# can't use cranelift here bcuz wasmtime no likey :(
# https://github.com/rust-lang/rustc_codegen_cranelift/issues/1204
# codegen-backend = "cranelift"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-Clink-arg=-fuse-ld=/usr/bin/mold",
    "-Clink-arg=-Wl,--no-rosegment",
]

[alias]
xtask = "run --package xtask --"
