[workspace]

members = [
  "cubedaw",
  "cubedaw_lib",
  "cubedaw_worker",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.71.1"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2
